### ISSUE TITLE
Ensure valid local channel

### ISSUE THREAD

**Issue by kcpevey** [MetroStar/ib_manifest_util#28]
## Summary

Test that we can build an environment from our local channel with `--offline` 

* This arose from the recent issue with `repodata.json`. This test is designed to catch that failure in the future. 

## Acceptance Criteria
a new test exists

**Comment by kcpevey** [comment]
add a new function into `util` called `verify_local_channel_environments` (name is up for discussion)
This function will:
* accept an environment file (which should point to a local channel)
* ensure that the local channel exists at the location in the environment file
* successfully run `conda env create -f env.yml --offline` (or mamba?)

**Comment by iameskild** [comment]
As I work on this, I realize that we'll need to either wait for a fix for this [`conda-vendor` issue](https://github.com/MetroStar/conda-vendor/issues/38) or modify the `repodata.json` in-place to avoid running into the same issue reported in the linked issue.

**Comment by iameskild** [comment]
I decided that fixing the upstream issue mades the most sense.
https://github.com/MetroStar/conda-vendor/pull/39
