### ISSUE TITLE
Improve tests for write_templatized_file

### ISSUE THREAD

**Issue by tylerpotts** [MetroStar/ib_manifest_util#5]
per @ericdatakelly 

## Summary

`write_templatized _file` needs tests.  https://github.com/metrostar/ib_manifest_util/blob/main/ib_manifest_util/util.py#L18

## Acceptance Criteria

- Tests that cover the function run on ci

## Related to

#1 

Looks like we already have a test for this. @kcpevey does the test need more work or should we close this issue?

---
per @kcpevey 

hardening_manifest_path = TEST_DATA_DIR.joinpath("hardening_manifest.yaml") should be output_path.

All the paths and the contents should be moved into conf.py so that they can be reused (potentially as fixtures).

contents is the contents of hardening_manifest.yml so its variable name should reflect that.

**Comment by ericdatakelly** [comment]
@kcpevey Let me know if this is going where you were planning.

**Comment by ericdatakelly** [comment]
> @kcpevey Let me know if this is going where you were planning.

Oops... meant to post in the PR.
