### ISSUE TITLE
Set up branches for development

### ISSUE THREAD

**Issue by ericdatakelly** [MetroStar/ib_manifest_util#8]
## Summary

We need a `dev` branch for PRs and testing code so that we don't push new code to `main` without thorough testing.

## Proposed implementation

- Create a `dev` branch and set it as the default branch

**Comment by ericdatakelly** [comment]
@kcpevey how do you want this set up?  Should we consider versioning now or later?

**Comment by rycrow** [comment]
Should be good to go, `dev` is set as default.
